[package]
name = "yrs"
version = "0.1.0"
authors = ["realth000 <a598919335@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
tui = { package = "ratatui", version = "0.21.0" }
